### PR TITLE
fix: fix ignore-scripts

### PR DESCRIPTION
**Pull request by jayree**

### CODE REVIEW

**Review by shetzel — APPROVED** [review]

**Comment by iowillhoit** [comment]
Hey @jayree, the string fix looks good on the `--ignore-scripts` input.  
Could your revert the version bumps on the external Actions though? We use these same actions in several places and we perform a manual code review before bumping them everywhere. If these are block you, I can create a ticket to prioritize bumping these versions

**Comment by jayree** [comment]
@iowillhoit done. The version bumps were `Node.js 16` related. FYI: It seems that some of the actions used by this repo are no longer actively maintained.

**Review by iowillhoit — APPROVED** [review]

**Comment by iowillhoit** [comment]
Thanks @jayree, a while ago we did an audit of these actions and replaced ones that were abandoned. I'll get a ticket created to look at these too

**Comment by iowillhoit** [comment]
[@W-15727365@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-15727365)

**Pull request merged**
